In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

Couldn't import dot_parser, loading of dot files will not be possible.


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 21s 2us/step


In [20]:
x_test.shape

(10000, 28, 28)

In [24]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(x_test, y_test, test_size=0.2, random_state=42)

(8000, 28, 28)

In [31]:
a = np.array([[1,5,9],[2,6,10]])
b = np.array([[3,7,11],[4,8,12]])

In [32]:
print np.concatenate((a,b),axis=0)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [33]:
print np.concatenate((a,b),axis=1)

[[ 1  5  9  3  7 11]
 [ 2  6 10  4  8 12]]


In [38]:
x_new_train = np.concatenate((x_train,X_tr),axis=0)
y_new_train = np.concatenate((y_train,y_tr),axis=0)
x_new_test = X_te
y_new_test = y_te

In [39]:
x_new_train.shape

(68000, 28, 28)

In [40]:
y_new_train.shape

(68000,)

In [43]:
x_new_test.shape

(2000, 28, 28)

In [44]:
y_new_test.shape

(2000,)